CREATE TABLE leaderboard (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player VARCHAR(255) NOT NULL,
    difficulty VARCHAR(255) NOT NULL,
    best_streak INTEGER NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_leaderboard_player_difficulty UNIQUE (player, difficulty)
);
